tap "caskroom/cask"
tap "caskroom/versions"
tap "homebrew/bundle"
tap "homebrew/core"
brew "cdrtools"
brew "cntlm"
brew "docker-compose"
brew "git"
brew "gnupg"
brew "go"
brew "jq"
brew "ncdu"
brew "node"
brew "packer"
brew "qemu", args: ["with-sdl2"]
brew "tmux"
brew "vault"
brew "vim", args: ["with-override-system-vi"]
brew "wget"
cask "duplicati"
cask "google-chrome"
cask "iterm2"
cask "karabiner-elements"
cask "p4merge"
cask "powershell"
cask "virtualbox"
cask "visual-studio-code"
cask "caskroom/versions/java8"
