tap "caskroom/cask"
tap "caskroom/versions"
tap "homebrew/bundle"
tap "homebrew/core"
tap "homebrew/services"
brew "cdrtools"
brew "cntlm", restart_service: true
brew "git"
brew "gnupg"
brew "go"
brew "gopass"
brew "jq"
brew "kubernetes-cli"
brew "mono"
brew "ncdu"
brew "netcat"
brew "node"
brew "packer"
brew "qemu", args: ["with-sdl2"]
brew "tmux"
brew "vault"
brew "vim", args: ["with-override-system-vi"]
brew "wget"
brew "zsh"
cask "cord"
cask "duplicati"
cask "flycut"
cask "google-chrome"
cask "iterm2"
cask "karabiner-elements"
cask "p4merge"
cask "powershell"
cask "sourcetree"
cask "virtualbox"
cask "visual-studio-code"
cask "caskroom/versions/docker-edge"
cask "caskroom/versions/java8"
