#!/usr/bin/env bash

# source env file
dotenv "$HOME/.env"
if [ -f "$HOME/.local.env" ]; then
    dotenv "$HOME/.local.env"
fi

# Add gopath/bin to path
export PATH=$GOPATH/bin:$PATH

# Avoid issues with `gpg` as installed via Homebrew.
# https://stackoverflow.com/a/42265848/96656
export GPG_TTY=$(tty);

# Don't check mail when opening terminal.
unset MAILCHECK
