#!/usr/bin/env bash

# source env file
eval $(${DOTFILES_DIR}/.bin/vendor/envy.sh/envy.sh "$HOME/.env")

if [ -f "$HOME/.local.env" ]; then
    eval $(${DOTFILES_DIR}/.bin/vendor/envy.sh/envy.sh "$HOME/.local.env")
fi
