#!/bin/bash

proxy_print() {
    echo http_proxy=$http_proxy;
    echo https_proxy=$https_proxy;
    echo noproxy=$no_proxy
    if [ "$(uname)" = "Darwin" ]; then
        brew services list
    fi
}

proxy_unset() {
    unset NO_PROXY ALL_PROXY HTTP_PROXY HTTPS_PROXY no_proxy all_proxy http_proxy https_proxy
    proxy_print
}

proxy_enable() {
    export NO_PROXY=$_NO_PROXY
    export ALL_PROXY=$_HTTP_PROXY
    export HTTP_PROXY=$_HTTP_PROXY
    export HTTPS_PROXY=$_HTTPS_PROXY

    export no_proxy=$_NO_PROXY
    export all_proxy=$_HTTP_PROXY
    export http_proxy=$_HTTP_PROXY
    export https_proxy=$_HTTPS_PROXY

    if [ ! -e $HOME/.proxy_enable ]; then
        if [ -n "$BASH_VERSION" ]; then
            bash-it enable plugin proxy
            enable-proxy
        fi
        if [ "$(uname)" = "Darwin" ]; then
            networksetup -switchtolocation "Automatic" > /dev/null
        fi
        touch $HOME/.proxy_enable
    fi
}

proxy_disable() {
    proxy_unset

    if [ -e $HOME/.proxy_enable ]; then
        rm -f $HOME/.proxy_enable
        if [ "$(uname)" = "Darwin" ]; then
            networksetup -switchtolocation "No Proxy" > /dev/null
        fi
    fi
}

proxy_check() {
    if [ -e $HOME/.proxy_enable ]; then
        proxy_enable
    fi
}
