#!/bin/bash

if [ -n "$ZSH_VERSION" ]; then
    DIR="$( cd "$( dirname "${(%):-%N}" )" && pwd )"
elif [ -n "$BASH_VERSION" ]; then
    DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
fi

if [ -L $DIR ]; then
    DIR="$(readlink $DIR)"
fi

export DOTFILES_DIR="$(dirname $DIR)"

for f in $(ls $DOTFILES_DIR/.bash/inc/); do
    source $DOTFILES_DIR/.bash/inc/$f
done
