#!/usr/bin/env bash

# source env file
dotenv "$HOME/.env"

# Add gopath/bin to path
export PATH=$GOPATH/bin:$PATH

# Avoid issues with `gpg` as installed via Homebrew.
# https://stackoverflow.com/a/42265848/96656
export GPG_TTY=$(tty);